apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS dbecommerce_produk;
    CREATE DATABASE IF NOT EXISTS dbecommerce_orders;
    CREATE DATABASE IF NOT EXISTS dbecommerce_payment;
    CREATE DATABASE IF NOT EXISTS dbecommerce_customer;
    
    CREATE USER IF NOT EXISTS 'userdb'@'%' IDENTIFIED BY 'passworddb';
    GRANT ALL PRIVILEGES ON dbecommerce_produk.* TO 'userdb'@'%';
    GRANT ALL PRIVILEGES ON dbecommerce_orders.* TO 'userdb'@'%';
    GRANT ALL PRIVILEGES ON dbecommerce_payment.* TO 'userdb'@'%';
    GRANT ALL PRIVILEGES ON dbecommerce_customer.* TO 'userdb'@'%';
    
    FLUSH PRIVILEGES;
